[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
nvim-oxi = {features = ["neovim-0-9", "libuv", "oxi-libuv"], version = "0.3"}
tiny-skia = "0.11.4"
syntect = "5.2.0"
cosmic-text = "0.11.2"
serde = "1.0.197"
arboard = "3.3.2"

[lib]
crate-type = ["cdylib"]
