[project]
name = "codesnap.nvim"
version = "2.0.0-beta.2"
description = "ðŸ“¸ Snapshot plugin that can make pretty code snapshots with real-time previews for Neovim"
author = "Mist"
email = "mist.zzh@gmail.com"
