[project]
name = "codesnap.nvim"
version = "1.6.0"
description = "ðŸ“¸ Snapshot plugin that can make pretty code snapshots with real-time previews for Neovim"
author = "Mist"
email = "mist.zzh@gmail.com"
